#!/usr/bin/python2.7
#
# Cryptocompare get API data
#
# Copyright (C) 2017  Pavle Obradovic (pajaja)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import urllib, json
from os.path import expanduser

# Select currency pairs
from_currencies = ['BTC', 'ETH', 'XMR', 'XRP', 'ZEC']
to_currencies = ['USD']

# Cryptocompare API URL. Watch for request rate per hour.
# We're using Bitfinex exchange
base_url = "https://min-api.cryptocompare.com/data/pricemulti"
url = base_url + "?fsyms=" + ','.join(from_currencies) + "&tsyms=" + ','.join(to_currencies) + "&e=Bitfinex"

# Part one - Get current (old) data from file
try:
    data_file = open(expanduser('~/.cryptocompare-last'), 'r')
    data = json.loads(data_file.read())

except Exception:
    # If no file is present build empty data dict
    data = {
        'old': {},
        'new': {}
    }

try:
    # Fetch new data from API
    response = urllib.urlopen(url)
    api_response = json.loads(response.read())

    # Open file to write new data in
    data_file = open(expanduser('~/.cryptocompare-last'), 'w+')

    # Save previously saved data as old and data fetched from API as new
    data['old'] = data['new']
    data['new'] = api_response

    # Save new data and close file
    data_file.write(json.dumps(data))
    data_file.close()

except Exception:
    exit(1)
