#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
#
# ICMP check
# Checks if devices responds to ICMP requests
#
# Copyright (C) 2017  Pavle Obradovic (pajaja)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

reload(sys)
sys.setdefaultencoding('utf8')

# List of devices to ping
hostnames = [
    '109.122.96.1',
    'core-sc-1.vektor.net',
    'border-sc-1.vektor.net',
    'l3-gs-1.vektor.net',
    'core-bo-1.vektor.net',
    'core-ob-1.vektor.net',
    'edge-ba-1.vektor.net',
    'pajaja.aur.co.rs'
]

string = ""


for host in hostnames:
    response = os.system("ping -c 1 " + host + " >/dev/null 2>&1")

    if response == 0:
        string += "<span color='#baffba'>●</span>"
    else:
        string += "<span color='#ff0000'>●</span>"

print string
