#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
#
# Port listening check
# Checks if localhost listens on specific ports
#
# Copyright (C) 2017  Pavle Obradovic (pajaja)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import subprocess
import shlex
import re

reload(sys)
sys.setdefaultencoding('utf8')

# Define services and what to match
# Key will be displayed to output
# Value will be escaped and used for regexp matching
services = {
    'ssh': " 0.0.0.0:22 ",
    'vnc': " 0.0.0.0:5900 ",
    'mysql': " 0.0.0.0:3306 "
}

# Output array
output = []

# /dev/null for stderr output
with open(os.devnull, 'wb') as devnull:
    proc_list = subprocess.Popen(shlex.split('netstat -tulpn'), stdout=subprocess.PIPE, stderr=devnull)
    proc_list_output = proc_list.communicate()[0]

    # Go trough the list of services and match each line from netstat output
    for service, match in services.iteritems():
        running = False
        compiled = re.compile(re.escape(match))
        for line in proc_list_output.split("\n"):
            if compiled.search(line):
                # If the line matches, service is running
                running = True
                break

        if running:
            output.append("<span color='#baffba'>%s</span>" % service.upper())
        else:
            output.append("<span color='#ff0000'>%s</span>" % service.upper())

print '  '.join(output)
