#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

"""
Script showing how much hours of work is left today
"""

import sys
import datetime
import math

reload(sys)
sys.setdefaultencoding('utf8')


def lvmap(value, x_start, x_end, u_start, u_end):
    return u_start + ((u_end-u_start) * ((value-x_start)/(x_end-x_start)))

work = {
    'start': {
        'hour': 10,
        'minute': 0
    },
    'duration': 8
}

today = datetime.datetime.today()
start = today.replace(hour=work['start']['hour'], minute=work['start']['minute'], second=0, microsecond=0)
finish = start + datetime.timedelta(hours=work['duration'])

if today < start:
    print '○○○○○○○○'
elif today >= start:
    if today <= finish:
        work_done = lvmap((today-start).total_seconds(), 0, 8*3600, 0, 8)
        dots = int(math.floor(work_done))
        reminder = work_done % 1

        return_string = ""
        #Completed dots
        return_string += "<span color='#00ff00'>%s</span>" % (
            '●' * dots,
        )
        # Current dot
        # Change color from white to green depending on how much time passed
        # G value is always 255, R and B values change from 255 to 0 by mapping reminder to [0,255]
        reminder_color = "{0:02x}".format(255-int(lvmap(reminder, 0, 1, 0, 255)))
        return_string += "<span color='#%sff%s'>%s</span>" % (
            reminder_color, reminder_color, '●'
        )
        # Empty dots
        return_string += "<span>%s</span>" % (
            '○' * (8 - (dots+1))
        )
        print return_string
    else:
        print '<span color=\'#00ff00\'>●●●●●●●●</span>'